config/routes.rb
BusinessCard::Application.routes.draw do
  devise_for :login_users
  resources :companies do
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  root :to => "companies#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  paginates_per 5
  belongs_to :company
  has_many :users, :dependent => :destroy
  validates :name, presence:{message:'入力してください'}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    company = Company.find(params[:company_id])
    #@groups = company.groups
    @groups = company.groups.order(:name).page params[:page] 
  end

  def show
  end

  def new
    company = Company.find(params[:company_id])
    @group = company.groups.new
  end

  def create
    company = Company.find(params[:company_id]) 
    @group = company.groups.build(group_params)
    if @group.save
      redirect_to company_groups_path(params[:company_id])
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to company_group_path(@group.company_id,@group.id), notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to company_groups_path(params[:company_id])
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params[:group].permit(:name)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= params[:action]%>
<%= form_for @group, :url => {:action => params[:action] == 'new' ? 'create' : (params[:action] == 'edit') ? 'update' : 'create'} do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>
<%= render 'form' %>
<%= link_to 'Back', company_groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, company_group_path(group.company_id, group.id)%></td>
        <td><%= link_to 'ShowUsers', company_group_users_path(group.company_id,group.id)%>
        <td><%= link_to 'Edit', edit_company_group_path(group.company_id,group.id) %></td>
        <td><%= link_to 'Destroy', company_group_path(group.company_id,group.id ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @groups %>
<%= link_to 'New Group', new_company_group_path %>
<%= link_to 'back Companies', companies_path%>

app/views/groups/new.html.erb
<h1>New group</h1>
<%= render 'form' %>
<%= link_to 'Back', company_groups_path(@group.company_id) %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Group Information</h1>
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<%= link_to 'Edit', edit_company_group_path %>
<%= link_to 'Back', company_groups_path %>