config/routes.rb
BusinessCard::Application.routes.draw do
  devise_for :login_users
  resources :companies do
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  root :to => "companies#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  paginates_per 5
  has_many :groups, :dependent => :destroy
  
  validates :name,presence:{message:'社名を入力してください'}, 
                  length:{ maximum: 100, message:"100文字以内で入力してください"}

  validates :tel, format:{ with: /[0-9]{4}-[0-9]{3}-[0-9]{4}/,
                           allow_nil: true,
                           allow_blank: true,
                           message:"電話番号は0000-000-0000の形式で入力してください"
                          },
                  length:{ maximum: 13}

  validates :fax,  format:{ with: /[0-9]{4}-[0-9]{3}-[0-9]{4}/,
                          allow_nil: true,
                          allow_blank: true,
                          message:"FAX番号は0000-000-0000の形式で入力してください"
                          },
                   length:{ maximum: 13}

  validates :adress, length:{maximum: 100},
                     presence:{message:"住所を入力してください"} 
 
  validates :url, presence:{message:"URLを入力してください"},
                  length:{ maximum: 56, message:"56文字以内で入力してください"}
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # GET /companies
  # GET /companies.json
  def index
    #@companies = Company.all
    if ! login_user_signed_in?
      redirect_to login_user_session_path
    end
    @companies = Company.order(:name).page params[:page]
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    redirect_to companies_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :adress, :tel, :fax, :url)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company_path(company.id) %></td>
        <td><%= link_to 'ShowGroups', company_groups_path(company.id)%>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @companies %>
<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Company Information</h1>
<ul>
  <li><strong>Name:</strong>
  <%= @company.name %>
  <li><strong>Adress:</strong>
  <%= @company.adress %>
  <li><strong>Tel:</strong>
  <%= @company.tel %>
  <li><strong>Fax:</strong>
  <%= @company.fax %>
  <li><strong>Url:</strong>
  <%= @company.url %>
</ul>
<%= link_to 'Edit Company Information', edit_company_path(@company) %> |
<%= link_to 'Back Companies Index', companies_path %>